export default interface Student{
    docid?: String,
    name: String,
    email: String,
    phoneno: Number,
    rollno: Number,
    hclgname: String,
    hyearpassing: Number,
    hmarks: Number,
    houtof: Number,
    hpercentage: Number,
    sclgname: String,
    syearpassing: Number,
    smarks: Number,
    soutof: Number,
    spercentage: Number,
    gsem1: Number,
    gsem2: Number,
    gsem3: Number,
    gsem4: Number,
    filename?: String,
    cgpi:Number,
    gper:Number,  
}